name: 'Datadog Dashboard Lister'
description: 'Retrieve a filtered set of dashboards'
inputs:
  datadog-api-key:
    description: 'Datadog API Key'
    required: true
  datadog-app-key:
    description: 'Datadog APP Key'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
